"""BibTeX export for the project's imported documents.

A ``.bib`` entry describes a *work*; a reference in this project describes a
*passage inside* a work. The generated file therefore carries one entry per
document, and the page a reference points at travels in the accompanying
``\\cite[p.~12]{key}`` command, which is where LaTeX expects a locator. Putting
the page in the entry instead would produce one bogus "work" per quotation.

Metadata comes from the imported PDF and is often incomplete. Missing fields
are omitted and reported, never filled in from general knowledge — the same
rule the summaries follow.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass, field
from typing import Any

from .documents import Document
from .references import Reference

ENTRY_TYPE = "misc"

HEADER = (
    "% Bibliography generated by Litmark from the imported PDFs.\n"
    "% Fields come from each document's own metadata; unknown fields are\n"
    "% omitted rather than guessed. Page locators belong in the \\cite\n"
    "% commands, not here: an entry is a work, not a passage.\n"
)

# BibTeX keys may not contain whitespace or any of ,{}()="#%'\ — building them
# from folded ASCII letters and digits keeps them valid by construction.
_KEY_ALLOWED_RE = re.compile(r"[^a-z0-9]+")
_AUTHOR_SPLIT_RE = re.compile(r"\s+and\s+|;|&")
_STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "by", "for", "from", "in", "is", "of",
    "on", "or", "the", "to", "with",
}

_ESCAPE = {
    "\\": r"\textbackslash{}",
    "{": r"\{",
    "}": r"\}",
    "$": r"\$",
    "&": r"\&",
    "%": r"\%",
    "#": r"\#",
    "_": r"\_",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def escape_bibtex(value: str) -> str:
    """Escape BibTeX's special characters and flatten whitespace.

    Escaping happens per character, so the braces introduced by a replacement
    such as ``\\textbackslash{}`` are not escaped a second time. Accented
    letters are left as UTF-8; biber reads them directly.
    """
    escaped = "".join(_ESCAPE.get(char, char) for char in value)
    return " ".join(escaped.split())


@dataclass
class BibEntry:
    key: str
    document_id: str
    title: str
    fields: list[tuple[str, str]]
    unknown: list[str] = field(default_factory=list)
    reference_ids: list[str] = field(default_factory=list)
    entry_type: str = ENTRY_TYPE

    def to_bibtex(self) -> str:
        lines = [f"@{self.entry_type}{{{self.key},"]
        for name, value in self.fields:
            # The title keeps a second pair of braces so BibTeX styles cannot
            # lowercase a proper noun in it.
            wrapped = f"{{{value}}}" if name == "title" else value
            lines.append(f"  {name} = {{{wrapped}}},")
        lines.append("}")
        return "\n".join(lines)

    def api_json(self) -> dict[str, Any]:
        return {
            "key": self.key,
            "document_id": self.document_id,
            "title": self.title,
            "entry_type": self.entry_type,
            "fields": dict(self.fields),
            "unknown_fields": self.unknown,
            "reference_ids": self.reference_ids,
            "bibtex": self.to_bibtex(),
        }


@dataclass
class Bibliography:
    entries: list[BibEntry] = field(default_factory=list)
    citations: list[dict[str, Any]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_bibtex(self) -> str:
        """The file's exact contents.

        Deliberately free of a timestamp: identical input produces identical
        bytes, so regenerating an unchanged bibliography rewrites nothing.
        """
        body = "\n\n".join(entry.to_bibtex() for entry in self.entries)
        return HEADER + ("\n" + body + "\n" if body else "")

    def api_json(self) -> dict[str, Any]:
        return {
            "entries": [entry.api_json() for entry in self.entries],
            "citations": self.citations,
            "warnings": self.warnings,
            "bibtex": self.to_bibtex(),
        }


def build_bibliography(
    documents: list[Document],
    references: dict[str, Reference],
    citations: dict[str, list[dict[str, str]]],
    *,
    cited_only: bool = False,
) -> Bibliography:
    """Assemble entries for ``documents`` and cite commands for ``references``.

    ``citations`` is the note-and-summary map from
    :func:`~litmark.references.citations_by_reference`; with
    ``cited_only`` it narrows the bibliography to the works a note or summary
    actually cites, which is what a paper's reference list should contain.
    """
    known = {document.document_id: document for document in documents}

    by_document: dict[str, list[Reference]] = {}
    orphaned: dict[str, list[str]] = {}
    for reference_id, reference in sorted(references.items()):
        if reference.document_id in known:
            by_document.setdefault(reference.document_id, []).append(reference)
        else:
            orphaned.setdefault(reference.document_id, []).append(reference_id)

    for refs in by_document.values():
        refs.sort(key=lambda ref: (ref.page_number, ref.reference_id))

    selected = [
        document
        for document in sorted(documents, key=lambda item: item.document_id)
        if not cited_only
        or any(
            citations.get(reference.reference_id)
            for reference in by_document.get(document.document_id, [])
        )
    ]

    entries: list[BibEntry] = []
    used: set[str] = set()
    for document in selected:
        entries.append(
            _entry_for(document, _unique_key(citation_key(document), used), by_document)
        )

    keys = {entry.document_id: entry.key for entry in entries}
    cite_commands: list[dict[str, Any]] = []
    for entry in entries:
        for reference in by_document.get(entry.document_id, []):
            locator = reference.page_label or str(reference.page_number)
            cite_commands.append(
                {
                    "reference_id": reference.reference_id,
                    "key": keys[entry.document_id],
                    "document_id": entry.document_id,
                    "page_number": reference.page_number,
                    "page_label": reference.page_label,
                    "cite": f"\\cite[p.~{locator}]{{{keys[entry.document_id]}}}",
                    "cited_by": citations.get(reference.reference_id, []),
                }
            )

    return Bibliography(
        entries=entries,
        citations=cite_commands,
        warnings=_warnings(entries, orphaned, cited_only=cited_only),
    )


def citation_key(document: Document) -> str:
    """``researcher2016mobility``-style key, or the document ID when unknown.

    Without an author the title word leads instead (``mobility2026``), because
    a key beginning with a digit reads badly and some tooling dislikes it. With
    neither an author nor a usable year the key would rest entirely on a title
    that was itself guessed from the first line of the PDF, so the document ID
    is used: less decorative, but stable and unique.
    """
    surname = _fold(_first_surname(document.authors))
    year = str(document.year) if document.year else ""
    word = _fold(_title_word(document.title or document.display_title))
    if surname:
        return f"{surname}{year}{word}"
    if year and word:
        return f"{word}{year}"
    return _KEY_ALLOWED_RE.sub("-", document.document_id.lower()).strip("-")


def authors_field(raw: str) -> str:
    """Normalize a PDF author string into BibTeX's ``X and Y`` form.

    ``/Author`` is free text: it may already use "and", or semicolons, or
    commas — and a comma is ambiguous, separating a list in "Alice Researcher,
    Bob Coauthor" but a single surname-first name in "Researcher, Alice". The
    parts are only split on a comma when every part looks like a whole name.
    """
    parts = [part.strip() for part in _AUTHOR_SPLIT_RE.split(raw) if part.strip()]
    if len(parts) == 1 and "," in parts[0]:
        chunks = [chunk.strip() for chunk in parts[0].split(",") if chunk.strip()]
        if len(chunks) > 1 and all(len(chunk.split()) > 1 for chunk in chunks):
            parts = chunks
    return " and ".join(parts)


# ------------------------------------------------------------------ internals


def _entry_for(
    document: Document, key: str, by_document: dict[str, list[Reference]]
) -> BibEntry:
    fields: list[tuple[str, str]] = []
    unknown: list[str] = []

    if document.authors and document.authors.strip():
        fields.append(("author", escape_bibtex(authors_field(document.authors))))
    else:
        unknown.append("author")

    title = document.display_title
    fields.append(("title", escape_bibtex(title)))

    if document.year:
        fields.append(("year", str(document.year)))
    else:
        unknown.append("year")

    # A project-relative path, so the file stays valid when the project moves.
    stored = document.pdf.get("path") or f"documents/{document.document_id}/original.pdf"
    fields.append(("file", escape_bibtex(str(stored))))

    return BibEntry(
        key=key,
        document_id=document.document_id,
        title=title,
        fields=fields,
        unknown=unknown,
        reference_ids=[
            reference.reference_id for reference in by_document.get(document.document_id, [])
        ],
    )


def _unique_key(base: str, used: set[str]) -> str:
    """Two papers by the same author in the same year must not share a key."""
    candidate = base
    suffix = ord("a")
    while candidate in used:
        candidate = f"{base}{chr(suffix)}"
        suffix += 1
    used.add(candidate)
    return candidate


def _first_surname(authors: str | None) -> str:
    if not authors or not authors.strip():
        return ""
    first = _AUTHOR_SPLIT_RE.split(authors.strip())[0].strip()
    head = first.split(",")[0].strip() if "," in first else first
    tokens = head.split()
    if not tokens:
        return ""
    # "Researcher, Alice" leaves one token — the surname. "Alice Researcher"
    # leaves two, and the surname is the last of them.
    return tokens[-1]


def _title_word(title: str | None) -> str:
    for word in re.split(r"\W+", title or ""):
        if len(word) > 2 and word.lower() not in _STOPWORDS:
            return word
    return ""


def _fold(value: str) -> str:
    """ASCII-fold and strip to the characters a BibTeX key may contain."""
    decomposed = unicodedata.normalize("NFKD", value)
    ascii_only = "".join(char for char in decomposed if not unicodedata.combining(char))
    return _KEY_ALLOWED_RE.sub("", ascii_only.lower())


def _warnings(
    entries: list[BibEntry], orphaned: dict[str, list[str]], *, cited_only: bool
) -> list[str]:
    warnings: list[str] = []

    for label in ("author", "year"):
        affected = [entry.title for entry in entries if label in entry.unknown]
        if affected:
            subject = "the entry omits" if len(affected) == 1 else "the entries omit"
            warnings.append(
                f"No {label} in the PDF metadata for {_join(affected)}; "
                f"{subject} the {label} field rather than guessing it."
            )

    for document_id, reference_ids in sorted(orphaned.items()):
        warnings.append(
            f"{_join(reference_ids)} cite {document_id}, which is no longer in this "
            "project, so it has no entry."
        )

    if not entries:
        warnings.append(
            "No note or summary cites a reference yet, so the bibliography is empty."
            if cited_only
            else "This project has no documents yet, so the bibliography is empty."
        )
    return warnings


def _join(values: list[str]) -> str:
    if len(values) == 1:
        return values[0]
    return ", ".join(values[:-1]) + f" and {values[-1]}"
